// Copyright (c) 2025 Dmitry Kalashnikov.

use std::collections::HashMap;
use std::sync::OnceLock;

static SERVICE_MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

fn get_service_map() -> &'static HashMap<&'static str, &'static str> {
    SERVICE_MAP.get_or_init(|| {
        SERVICE_CAPABILITIES.iter().copied().collect()
    })
}

const SERVICE_CAPABILITIES: &[(&str, &str)] = &[
    ("1800", "Generic Access"),
    ("1801", "Generic Attribute"),
    ("1802", "Immediate Alert"),
    ("1803", "Link Loss"),
    ("1804", "Tx Power"),
    ("1805", "Current Time Service"),
    ("1806", "Reference Time Update"),
    ("1807", "Next DST Change"),
    ("1808", "Glucose"),
    ("1809", "Health Thermometer"),
    ("180a", "Device Information"),
    ("180d", "Heart Rate"),
    ("180e", "Phone Alert Status"),
    ("180f", "Battery Service"),
    ("1810", "Blood Pressure"),
    ("1811", "Alert Notification"),
    ("1812", "Human Interface Device"),
    ("1813", "Scan Parameters"),
    ("1814", "Running Speed and Cadence"),
    ("1815", "Automation IO"),
    ("1816", "Cycling Speed and Cadence"),
    ("1817", "Location and Speed"),
    ("1818", "Cycling Power"),
    ("1819", "Location and Navigation"),
    ("181a", "Environmental Sensing"),
    ("181b", "Body Composition"),
    ("181c", "User Data"),
    ("181d", "Weight Scale"),
    ("181e", "Bond Management"),
    ("181f", "Continuous Glucose Monitoring"),
    ("1820", "Internet Protocol Support"),
    ("1821", "Indoor Positioning"),
    ("1822", "Pulse Oximeter"),
    ("1823", "HTTP Proxy"),
    ("1824", "Transport Discovery"),
    ("1825", "Object Transfer"),
    ("1826", "Fitness Machine"),
    ("1827", "Mesh Provisioning"),
    ("1828", "Mesh Proxy"),
    ("1829", "Reconnection Configuration"),
    ("183a", "Insulin Delivery"),
    ("183b", "Binary Sensor"),
    ("183c", "Emergency Configuration"),
    ("183d", "Authorization Control"),
    ("183e", "Physical Activity Monitor"),
    ("183f", "Audio Input Control"),
    ("1840", "Volume Control"),
    ("1841", "Volume Offset Control"),
    ("1842", "Coordinated Set Identification"),
    ("1843", "Device Time"),
    ("1844", "Media Control"),
    ("1845", "Generic Media Control"),
    ("1846", "Constant Tone Extension"),
    ("1847", "Telephone Bearer"),
    ("1848", "Generic Telephone Bearer"),
    ("1849", "Microphone Control"),
    ("184a", "Audio Stream Control"),
    ("184b", "Broadcast Audio Scan"),
    ("184c", "Published Audio Capabilities"),
    ("184d", "Basic Audio Announcement"),
    ("184e", "Broadcast Audio Announcement"),
    ("184f", "Common Audio"),
    ("1850", "Hearing Access"),
    ("1851", "TMAS"),
    ("1852", "Public Broadcast Announcement"),
    ("1853", "Electronic Shelf Label"),
    ("1854", "Gaming Audio"),
    ("1855", "Coordinated Media"),
    ("1856", "Microphone Controller"),
    ("1857", "Speaker Controller"),
    ("febe", "Tile"),
    ("fed8", "Fitbit"),
    ("fed9", "Google Fast Pair"),
    ("feaa", "Eddystone"),
    ("fedc", "Garmin"),
    ("fea0", "Samsung"),
    ("fe2c", "Apple Media Service"),
    ("fe95", "Xiaomi IoT"),
    ("fe9f", "Google Nearby"),
    ("fd6f", "Exposure Notification"),
    ("fee0", "Polar"),
    ("fee1", "WAHOO Fitness"),
    ("fee7", "Suunto"),
    ("15b9", "Siri"),
    ("fe26", "Apple Continuity"),
    ("fe27", "Apple AirDrop"),
    ("fe28", "Apple HomeKit"),
    ("fe29", "Apple Notification Center"),
    ("d0", "Apple iBeacon"),
    ("fe2b", "Apple AirPods"),
    ("fe2a", "Apple Media Remote"),
    ("feab", "Facebook Messenger"),
    ("feac", "Tencent QQ"),
    ("fead", "Alibaba"),
    ("feae", "Microsoft"),
    ("feaf", "Nordic Semiconductor"),
    ("feb0", "Gimbal"),
    ("feb1", "Estimote"),
    ("feb2", "Currant"),
    ("feb3", "June Life"),
    ("feb4", "Google Glass"),
    ("feb5", "Quintic"),
    ("feb6", "Dialog Semiconductor"),
    ("feb7", "Intel"),
    ("feb8", "Emerson"),
    ("feb9", "Philips"),
    ("feba", "CSR"),
    ("febb", "Laird Technologies"),
    ("febc", "Dexcom"),
    ("febd", "Polar Electro"),
    ("febf", "Qualcomm"),
    ("fec0", "Qualcomm Connected Spaces"),
    ("fec1", "Plantronics"),
    ("fec2", "Broadcom"),
    ("fec3", "Abbott Diabetes Care"),
    ("fec4", "Procter & Gamble"),
    ("fec5", "GoPro"),
    ("fec6", "Amazon Alexa"),
    ("fec7", "Ayla Networks"),
    ("fec8", "Gibson"),
    ("fec9", "Sigma Sport"),
    ("feca", "Uber"),
    ("fecb", "MC10"),
    ("fecc", "LG Electronics"),
    ("fecd", "Google Chromium"),
    ("fece", "Bayerische Motoren Werke"),
    ("fecf", "Volkswagen"),
    ("fed0", "Volkswagen Group"),
    ("fed1", "Xiaomi"),
    ("fed2", "OnePlus"),
    ("fed3", "Huawei"),
    ("fed4", "Lenovo"),
    ("fed5", "Sonos"),
    ("fed6", "Microsoft Xbox"),
    ("fed7", "PayPal"),
    ("feda", "Facebook"),
    ("fedb", "LEGO"),
    ("fedd", "TerraTec"),
    ("fede", "GN ReSound"),
    ("fedf", "GN Hearing"),
    ("fee2", "Bose"),
    ("fee3", "Clarius Mobile Health"),
    ("fee4", "Bosch"),
    ("fee5", "AirFuel"),
    ("fee6", "Samsung SmartThings"),
    ("fee8", "Vizio"),
    ("fee9", "Tesla"),
    ("feea", "Nest"),
    ("feeb", "Under Armour"),
    ("feec", "Spotify"),
    ("feed", "August Home"),
    ("feee", "Yardian"),
    ("feef", "Withings"),
    ("fef0", "HP"),
    ("fef1", "Motorola"),
    ("fef2", "Sony"),
    ("fef3", "ASUS"),
    ("fef4", "Logitech"),
    ("fef5", "Fitbit Aria"),
    ("fef6", "Adidas"),
    ("fef7", "Daimler"),
    ("fef8", "Canon"),
    ("fef9", "Nikon"),
    ("fefa", "JBL"),
    ("fefb", "Harman Kardon"),
    ("fefc", "Beats"),
    ("fefd", "GoPro Hero"),
    ("fefe", "Apple Watch"),
    ("feff", "Pebble"),
    ("ff00", "Skoda Auto"),
    ("ff01", "Volkswagen Commercial"),
    ("ff02", "Porsche"),
    ("ff03", "Audi"),
    ("ff04", "SEAT"),
    ("ff05", "Bentley"),
    ("ff06", "Lamborghini"),
    ("ff07", "Bugatti"),
    ("ff08", "Ducati"),
    ("ff09", "Ford"),
    ("ff0a", "Lincoln"),
    ("ff0b", "Mercedes-Benz"),
    ("ff0c", "smart"),
    ("ff0d", "Maybach"),
    ("ff0e", "BMW"),
    ("ff0f", "Mini"),
    ("ff10", "Rolls-Royce"),
    ("ff11", "McLaren"),
    ("ff12", "Maserati"),
    ("ff13", "Alfa Romeo"),
    ("ff14", "Ferrari"),
    ("ff15", "Jaguar"),
    ("ff16", "Land Rover"),
    ("ff17", "Volvo"),
    ("ff18", "Geely"),
    ("ff19", "Lotus"),
    ("ff1a", "Aston Martin"),
    ("ff1b", "Bentley Motors"),
    ("ff1c", "Honda"),
    ("ff1d", "Acura"),
    ("ff1e", "Toyota"),
    ("ff1f", "Lexus"),
    ("ff20", "Mazda"),
    ("ff21", "Subaru"),
    ("ff22", "Nissan"),
    ("ff23", "Infiniti"),
    ("ff24", "Mitsubishi"),
    ("ff25", "Hyundai"),
    ("ff26", "Kia"),
    ("ff27", "Genesis"),
    ("ff28", "Chevrolet"),
    ("ff29", "GMC"),
    ("ff2a", "Cadillac"),
    ("ff2b", "Buick"),
    ("ff2c", "Chrysler"),
    ("ff2d", "Dodge"),
    ("ff2e", "Jeep"),
    ("ff2f", "Ram"),
    ("ff30", "Fiat"),
    ("ff31", "Peugeot"),
    ("ff32", "Citroën"),
    ("ff33", "DS Automobiles"),
    ("ff34", "Opel"),
    ("ff35", "Vauxhall"),
    ("ff36", "Renault"),
    ("ff37", "Dacia"),
    ("ff38", "Lada"),
    ("ff39", "Alpine"),
    ("ff3a", "Tata Motors"),
    ("ff3b", "Mahindra"),
    ("ff3c", "Suzuki"),
    ("ff3d", "Isuzu"),
    ("ff3e", "Yamaha"),
    ("ff3f", "Kawasaki"),
    ("ff40", "Harley-Davidson"),
    ("ff41", "KTM"),
    ("ff42", "Aprilia"),
    ("ff43", "Triumph"),
    ("ff44", "Royal Enfield"),
    ("ff45", "Indian Motorcycle"),
    ("ff46", "Can-Am"),
    ("ff47", "Polaris"),
    ("ff48", "Arctic Cat"),
    ("ff49", "Sea-Doo"),
    ("ff4a", "Ski-Doo"),
    ("ff4b", "Lynx"),
    ("ff4c", "Tesla Motors"),
    ("ff4d", "Rivian"),
    ("ff4e", "Lucid Motors"),
    ("ff4f", "Polestar"),
    ("ff50", "NIO"),
    ("ff51", "XPeng"),
    ("ff52", "BYD"),
    ("ff53", "Li Auto"),
    ("ff54", "Faraday Future"),
    ("ff55", "Fisker"),
    ("ff56", "Canoo"),
    ("ff57", "Lordstown Motors"),
    ("ff58", "Nikola"),
    ("ff59", "Arrival"),
    ("ff5a", "Ather Energy"),
    ("ff5b", "Ola Electric"),
    ("ff5c", "Hero Electric"),
    ("ff5d", "Revolt Motors"),
    ("ff5e", "Ultraviolette"),
    ("ff5f", "Zero Motorcycles"),
    ("ff60", "Energica"),
    ("ff61", "Lightning Motorcycles"),
    ("ff62", "Cake"),
    ("ff63", "Super Soco"),
    ("ff64", "NIU"),
    ("ff65", "Segway"),
    ("ff66", "Xiaomi Mijia"),
    ("ff67", "Ninebot"),
    ("ff68", "Inmotion"),
    ("ff69", "Gotway"),
    ("ff6a", "KingSong"),
    ("ff6b", "Begode"),
    ("ff6c", "Leaos"),
    ("ff6d", "VanMoof"),
    ("ff6e", "Cowboy"),
    ("ff6f", "Ride1Up"),
    ("ff70", "Rad Power Bikes"),
    ("ff71", "Super73"),
    ("ff72", "Juiced Bikes"),
    ("ff73", "Aventon"),
    ("ff74", "Pedego"),
    ("ff75", "Trek"),
    ("ff76", "Specialized"),
    ("ff77", "Giant"),
    ("ff78", "Cannondale"),
    ("ff79", "Scott"),
    ("ff7a", "Santa Cruz"),
    ("ff7b", "Pivot"),
    ("ff7c", "Ibis"),
    ("ff7d", "Yeti"),
    ("ff7e", "Intense"),
    ("ff7f", "Evil"),
    ("ff80", "Transition"),
    ("ff81", "Norco"),
    ("ff82", "Rocky Mountain"),
    ("ff83", "Kona"),
    ("ff84", "Salsa"),
    ("ff85", "Surly"),
    ("ff86", "All-City"),
    ("ff87", "Marin"),
    ("ff88", "Raleigh"),
    ("ff89", "Diamondback"),
    ("ff8a", "GT"),
    ("ff8b", "Mongoose"),
    ("ff8c", "Schwinn"),
    ("ff8d", "Huffy"),
    ("ff8e", "Kent"),
    ("ff8f", "Roadmaster"),
    ("ff90", "Genesis Bikes"),
    ("ff91", "Carrera"),
    ("ff92", "Boardman"),
    ("ff93", "Voodoo"),
    ("ff94", "Pinnacle"),
    ("ff95", "Pendleton"),
    ("ff96", "Apollo"),
    ("ff97", "Claud Butler"),
    ("ff98", "Dawes"),
    ("ff99", "Ridgeback"),
    ("ff9a", "Forme"),
    ("ff9b", "Ribble"),
    ("ff9c", "Planet X"),
    ("ff9d", "Kinesis"),
    ("ff9e", "Orange"),
    ("ff9f", "Whyte"),
    ("ffa0", "Charge"),
    ("ffa1", "Hope"),
    ("ffa2", "Cotic"),
    ("ffa3", "Bird"),
    ("ffa4", "Soma"),
    ("ffa5", "Rivendell"),
    ("ffa6", "Waterford"),
    ("ffa7", "Independent Fabrication"),
    ("ffa8", "Seven"),
    ("ffa9", "Moots"),
    ("ffaa", "Lynskey"),
    ("ffab", "Litespeed"),
    ("ffac", "Merlin"),
    ("ffad", "Airborne"),
    ("ffae", "Dean"),
    ("ffaf", "Kestrel"),
    ("ffb0", "Cervélo"),
    ("ffb1", "BMC"),
    ("ffb2", "Pinarello"),
    ("ffb3", "Colnago"),
    ("ffb4", "Bianchi"),
    ("ffb5", "De Rosa"),
    ("ffb6", "Wilier"),
    ("ffb7", "Cinelli"),
    ("ffb8", "Campagnolo"),
    ("ffb9", "Look"),
    ("ffba", "Time"),
    ("ffbb", "Lapierre"),
    ("ffbc", "Ridley"),
    ("ffbd", "Eddy Merckx"),
    ("ffbe", "Orbea"),
    ("ffbf", "BH"),
    ("ffc0", "Merida"),
    ("ffc1", "Fuji"),
    ("ffc2", "Felt"),
    ("ffc3", "Jamis"),
    ("ffc4", "Niner"),
    ("ffc5", "Devinci"),
    ("ffc6", "Juliana"),
    ("ffc7", "Liv"),
    ("ffc8", "Electra"),
    ("ffc9", "Breezer"),
    ("ffca", "Jamis Bikes"),
    ("ffcb", "Co-Motion"),
    ("ffcc", "Rodriguez"),
    ("ffcd", "Gunnar"),
    ("ffce", "Hampsten"),
    ("ffcf", "Eriksen"),
    ("ffd0", "Serotta"),
    ("ffd1", "Baum"),
    ("ffd2", "Colnago Master"),
    ("ffd3", "Pegoretti"),
    ("ffd4", "Gios"),
    ("ffd5", "Tommasini"),
    ("ffd6", "Passoni"),
    ("ffd7", "Chesini"),
    ("ffd8", "Casati"),
    ("ffd9", "Alan"),
    ("ffda", "Viner"),
    ("ffdb", "Guerciotti"),
    ("ffdc", "Pinarello Dogma"),
    ("ffdd", "Specialized S-Works"),
    ("ffde", "Trek Madone"),
    ("ffdf", "Cannondale SuperSix"),
    ("ffe0", "Scott Addict"),
    ("ffe1", "Giant TCR"),
    ("ffe2", "BMC Teammachine"),
    ("ffe3", "Cervélo R5"),
    ("ffe4", "Canyon Ultimate"),
    ("ffe5", "Cube"),
    ("ffe6", "Focus"),
    ("ffe7", "Rose"),
    ("ffe8", "Radon"),
    ("ffe9", "Stevens"),
    ("ffea", "Bergamont"),
    ("ffeb", "Ghost"),
    ("ffec", "Haibike"),
    ("ffed", "Winora"),
    ("ffee", "Kalkhoff"),
    ("ffef", "Raleigh Electric"),
    ("fff0", "Gazelle"),
    ("fff1", "Batavus"),
    ("fff2", "Sparta"),
    ("fff3", "Koga"),
    ("fff4", "Cortina"),
    ("fff5", "Giant E-Bike"),
    ("fff6", "Riese & Müller"),
    ("fff7", "Stromer"),
    ("fff8", "Specialized Turbo"),
    ("fff9", "Bulls"),
    ("fffa", "Flyer"),
    ("fffb", "Grace"),
    ("fffc", "M1 Sporttechnik"),
    ("fffd", "智米 Smartmi"),
    ("fffe", "小米 Mi"),
    ("ffff", "Generic Service"),
    ("2a00", "Device Name Characteristic"),
    ("2a01", "Appearance Characteristic"),
    ("2a02", "Peripheral Privacy Flag"),
    ("2a03", "Reconnection Address"),
    ("2a04", "Peripheral Preferred Connection Parameters"),
    ("2a05", "Service Changed"),
    ("2a06", "Alert Level"),
    ("2a07", "Tx Power Level"),
    ("2a08", "Date Time"),
    ("2a09", "Day of Week"),
    ("2a0a", "Day Date Time"),
    ("2a0b", "Exact Time 100"),
    ("2a0c", "Exact Time 256"),
    ("2a0d", "DST Offset"),
    ("2a0e", "Time Zone"),
    ("2a0f", "Local Time Information"),
    ("2a10", "Secondary Time Zone"),
    ("2a11", "Time with DST"),
    ("2a12", "Time Accuracy"),
    ("2a13", "Time Source"),
    ("2a14", "Reference Time Information"),
    ("2a15", "Time Broadcast"),
    ("2a16", "Time Update Control Point"),
    ("2a17", "Time Update State"),
    ("2a18", "Glucose Measurement"),
    ("2a19", "Battery Level"),
    ("2a1a", "Battery Power State"),
    ("2a1b", "Battery Level State"),
    ("2a1c", "Temperature Measurement"),
    ("2a1d", "Temperature Type"),
    ("2a1e", "Intermediate Temperature"),
    ("2a1f", "Temperature Celsius"),
    ("2a20", "Temperature Fahrenheit"),
    ("2a21", "Measurement Interval"),
    ("2a22", "Boot Keyboard Input Report"),
    ("2a23", "System ID"),
    ("2a24", "Model Number String"),
    ("2a25", "Serial Number String"),
    ("2a26", "Firmware Revision String"),
    ("2a27", "Hardware Revision String"),
    ("2a28", "Software Revision String"),
    ("2a29", "Manufacturer Name String"),
    ("2a2a", "IEEE 11073-20601 Regulatory Cert"),
    ("2a2b", "Current Time"),
    ("2a2c", "Magnetic Declination"),
    ("2a31", "Scan Refresh"),
    ("2a32", "Boot Keyboard Output Report"),
    ("2a33", "Boot Mouse Input Report"),
    ("2a34", "Glucose Measurement Context"),
    ("2a35", "Blood Pressure Measurement"),
    ("2a36", "Intermediate Cuff Pressure"),
    ("2a37", "Heart Rate Measurement"),
    ("2a38", "Body Sensor Location"),
    ("2a39", "Heart Rate Control Point"),
    ("2a3a", "Removable"),
    ("2a3b", "Service Required"),
    ("2a3c", "Scientific Temperature Celsius"),
    ("2a3d", "String"),
    ("2a3e", "Network Availability"),
    ("2a3f", "Alert Status"),
    ("2a40", "Ringer Control Point"),
    ("2a41", "Ringer Setting"),
    ("2a42", "Alert Category ID Bit Mask"),
    ("2a43", "Alert Category ID"),
    ("2a44", "Alert Notification Control Point"),
    ("2a45", "Unread Alert Status"),
    ("2a46", "New Alert"),
    ("2a47", "Supported New Alert Category"),
    ("2a48", "Supported Unread Alert Category"),
    ("2a49", "Blood Pressure Feature"),
    ("2a4a", "HID Information"),
    ("2a4b", "Report Map"),
    ("2a4c", "HID Control Point"),
    ("2a4d", "Report"),
    ("2a4e", "Protocol Mode"),
    ("2a4f", "Scan Interval Window"),
    ("2a50", "PnP ID"),
    ("2a51", "Glucose Feature"),
    ("2a52", "Record Access Control Point"),
    ("2a53", "RSC Measurement"),
    ("2a54", "RSC Feature"),
    ("2a55", "SC Control Point"),
    ("2a56", "Digital"),
    ("2a57", "Digital Output"),
    ("2a58", "Analog"),
    ("2a59", "Analog Output"),
    ("2a5a", "Aggregate"),
    ("2a5b", "CSC Measurement"),
    ("2a5c", "CSC Feature"),
    ("2a5d", "Sensor Location"),
    ("2a5e", "PLX Spot-Check Measurement"),
    ("2a5f", "PLX Continuous Measurement"),
    ("2a60", "PLX Features"),
    ("2a62", "Pulse Oximetry Control Point"),
    ("2a63", "Cycling Power Measurement"),
    ("2a64", "Cycling Power Vector"),
    ("2a65", "Cycling Power Feature"),
    ("2a66", "Cycling Power Control Point"),
    ("2a67", "Location and Speed"),
    ("2a68", "Navigation"),
    ("2a69", "Position Quality"),
    ("2a6a", "LN Feature"),
    ("2a6b", "LN Control Point"),
    ("2a6c", "Elevation"),
    ("2a6d", "Pressure"),
    ("2a6e", "Temperature"),
    ("2a6f", "Humidity"),
    ("2a70", "True Wind Speed"),
    ("2a71", "True Wind Direction"),
    ("2a72", "Apparent Wind Speed"),
    ("2a73", "Apparent Wind Direction"),
    ("2a74", "Gust Factor"),
    ("2a75", "Pollen Concentration"),
    ("2a76", "UV Index"),
    ("2a77", "Irradiance"),
    ("2a78", "Rainfall"),
    ("2a79", "Wind Chill"),
    ("2a7a", "Heat Index"),
    ("2a7b", "Dew Point"),
    ("2a7d", "Descriptor Value Changed"),
    ("2a7e", "Aerobic Heart Rate Lower Limit"),
    ("2a7f", "Aerobic Threshold"),
    ("2a80", "Age"),
    ("2a81", "Anaerobic Heart Rate Lower Limit"),
    ("2a82", "Anaerobic Heart Rate Upper Limit"),
    ("2a83", "Anaerobic Threshold"),
    ("2a84", "Aerobic Heart Rate Upper Limit"),
    ("2a85", "Date of Birth"),
    ("2a86", "Date of Threshold Assessment"),
    ("2a87", "Email Address"),
    ("2a88", "Fat Burn Heart Rate Lower Limit"),
    ("2a89", "Fat Burn Heart Rate Upper Limit"),
    ("2a8a", "First Name"),
    ("2a8b", "Five Zone Heart Rate Limits"),
    ("2a8c", "Gender"),
    ("2a8d", "Heart Rate Max"),
    ("2a8e", "Height"),
    ("2a8f", "Hip Circumference"),
    ("2a90", "Last Name"),
    ("2a91", "Maximum Recommended Heart Rate"),
    ("2a92", "Resting Heart Rate"),
    ("2a93", "Sport Type for Aerobic"),
    ("2a94", "Three Zone Heart Rate Limits"),
    ("2a95", "Two Zone Heart Rate Limit"),
    ("2a96", "VO2 Max"),
    ("2a97", "Waist Circumference"),
    ("2a98", "Weight"),
    ("2a99", "Database Change Increment"),
    ("2a9a", "User Index"),
    ("2a9b", "Body Composition Feature"),
    ("2a9c", "Body Composition Measurement"),
    ("2a9d", "Weight Measurement"),
    ("2a9e", "Weight Scale Feature"),
    ("2a9f", "User Control Point"),
    ("2aa0", "Magnetic Flux Density - 2D"),
    ("2aa1", "Magnetic Flux Density - 3D"),
    ("2aa2", "Language"),
    ("2aa3", "Barometric Pressure Trend"),
    ("2aa4", "Bond Management Control Point"),
    ("2aa5", "Bond Management Feature"),
    ("2aa6", "Central Address Resolution"),
    ("2aa7", "CGM Measurement"),
    ("2aa8", "CGM Feature"),
    ("2aa9", "CGM Status"),
    ("2aaa", "CGM Session Start Time"),
    ("2aab", "CGM Session Run Time"),
    ("2aac", "CGM Specific Ops Control Point"),
    ("2aad", "Indoor Positioning Configuration"),
    ("2aae", "Latitude"),
    ("2aaf", "Longitude"),
    ("2ab0", "Local North Coordinate"),
    ("2ab1", "Local East Coordinate"),
    ("2ab2", "Floor Number"),
    ("2ab3", "Altitude"),
    ("2ab4", "Uncertainty"),
    ("2ab5", "Location Name"),
    ("2ab6", "URI"),
    ("2ab7", "HTTP Headers"),
    ("2ab8", "HTTP Status Code"),
    ("2ab9", "HTTP Entity Body"),
    ("2aba", "HTTP Control Point"),
    ("2abb", "HTTPS Security"),
    ("2abc", "TDS Control Point"),
    ("2abd", "OTS Feature"),
    ("2abe", "Object Name"),
    ("2abf", "Object Type"),
    ("2ac0", "Object Size"),
    ("2ac1", "Object First-Created"),
    ("2ac2", "Object Last-Modified"),
    ("2ac3", "Object ID"),
    ("2ac4", "Object Properties"),
    ("2ac5", "Object Action Control Point"),
    ("2ac6", "Object List Control Point"),
    ("2ac7", "Object List Filter"),
    ("2ac8", "Object Changed"),
    ("2ac9", "Resolvable Private Address Only"),
    ("2acc", "Fitness Machine Feature"),
    ("2acd", "Treadmill Data"),
    ("2ace", "Cross Trainer Data"),
    ("2acf", "Step Climber Data"),
    ("2ad0", "Stair Climber Data"),
    ("2ad1", "Rower Data"),
    ("2ad2", "Indoor Bike Data"),
    ("2ad3", "Training Status"),
    ("2ad4", "Supported Speed Range"),
    ("2ad5", "Supported Inclination Range"),
    ("2ad6", "Supported Resistance Level Range"),
    ("2ad7", "Supported Heart Rate Range"),
    ("2ad8", "Supported Power Range"),
    ("2ad9", "Fitness Machine Control Point"),
    ("2ada", "Fitness Machine Status"),
    ("2adb", "Mesh Provisioning Data In"),
    ("2adc", "Mesh Provisioning Data Out"),
    ("2add", "Mesh Proxy Data In"),
    ("2ade", "Mesh Proxy Data Out"),
    ("2adf", "Average Current"),
    ("2ae0", "Average Voltage"),
    ("2ae1", "Boolean"),
    ("2ae2", "Chromatic Distance From Planckian"),
    ("2ae3", "Chromaticity Coordinates"),
    ("2ae4", "Chromaticity In CCT"),
    ("2ae5", "Chromaticity Tolerance"),
    ("2ae6", "CIE 13.3-1995 Color Rendering Index"),
    ("2ae7", "Coefficient"),
    ("2ae8", "Correlated Color Temperature"),
    ("2ae9", "Count 16"),
    ("2aea", "Count 24"),
    ("2aeb", "Country Code"),
    ("2aec", "Date UTC"),
    ("2aed", "Electric Current"),
    ("2aee", "Electric Current Range"),
    ("2aef", "Electric Current Specification"),
    ("2af0", "Electric Current Statistics"),
    ("2af1", "Energy"),
    ("2af2", "Energy In A Period Of Day"),
    ("2af3", "Event Statistics"),
    ("2af4", "Fixed String 16"),
    ("2af5", "Fixed String 24"),
    ("2af6", "Fixed String 36"),
    ("2af7", "Fixed String 8"),
    ("2af8", "Generic Level"),
    ("2af9", "Global Trade Item Number"),
    ("2afa", "Illuminance"),
    ("2afb", "Luminous Efficacy"),
    ("2afc", "Luminous Energy"),
    ("2afd", "Luminous Exposure"),
    ("2afe", "Luminous Flux"),
    ("2aff", "Luminous Flux Range"),
    ("2b00", "Luminous Intensity"),
    ("2b01", "Mass Flow"),
    ("2b02", "Perceived Lightness"),
    ("2b03", "Percentage 8"),
    ("2b04", "Power"),
    ("2b05", "Power Specification"),
    ("2b06", "Relative Runtime In A Current Range"),
    ("2b07", "Relative Runtime In A Generic Level Range"),
    ("2b08", "Relative Value In A Voltage Range"),
    ("2b09", "Relative Value In An Illuminance Range"),
    ("2b0a", "Relative Value In A Period Of Day"),
    ("2b0b", "Relative Value In A Temperature Range"),
    ("2b0c", "Temperature 8"),
    ("2b0d", "Temperature 8 In A Period Of Day"),
    ("2b0e", "Temperature 8 Statistics"),
    ("2b0f", "Temperature Range"),
    ("2b10", "Temperature Statistics"),
    ("2b11", "Time Decihour 8"),
    ("2b12", "Time Exponential 8"),
    ("2b13", "Time Hour 24"),
    ("2b14", "Time Millisecond 24"),
    ("2b15", "Time Second 16"),
    ("2b16", "Time Second 8"),
    ("2b17", "Voltage"),
    ("2b18", "Voltage Specification"),
    ("2b19", "Voltage Statistics"),
    ("2b1a", "Volume Flow"),
    ("2b1b", "Chromaticity Coordinate"),
    ("2b1c", "RC Feature"),
    ("2b1d", "RC Settings"),
    ("2b1e", "Reconnection Configuration Control Point"),
    ("2b1f", "IDD Status Changed"),
    ("2b20", "IDD Status"),
    ("2b21", "IDD Annunciation Status"),
    ("2b22", "IDD Features"),
    ("2b23", "IDD Status Reader Control Point"),
    ("2b24", "IDD Command Control Point"),
    ("2b25", "IDD Command Data"),
    ("2b26", "IDD Record Access Control Point"),
    ("2b27", "IDD History Data"),
    ("2b28", "Client Supported Features"),
    ("2b29", "Database Hash"),
    ("2b2a", "BSS Control Point"),
    ("2b2b", "BSS Response"),
    ("2b2c", "Emergency ID"),
    ("2b2d", "Emergency Text"),
    ("2b2e", "ACS Status"),
    ("2b2f", "ACS Data In"),
    ("2b30", "ACS Data Out Notify"),
    ("2b31", "ACS Data Out Indicate"),
    ("2b32", "ACS Control Point"),
    ("2b33", "Enhanced Blood Pressure Measurement"),
    ("2b34", "Enhanced Intermediate Cuff Pressure"),
    ("2b35", "Blood Pressure Record"),
    ("2b36", "Registered User"),
    ("2b37", "BR-EDR Handover Data"),
    ("2b38", "Bluetooth SIG Data"),
    ("2b39", "Server Supported Features"),
    ("2b3a", "Physical Activity Monitor Features"),
    ("2b3b", "General Activity Instantaneous Data"),
    ("2b3c", "General Activity Summary Data"),
    ("2b3d", "CardioRespiratory Activity Instantaneous Data"),
    ("2b3e", "CardioRespiratory Activity Summary Data"),
    ("2b3f", "Step Counter Activity Summary Data"),
    ("2b40", "Sleep Activity Instantaneous Data"),
    ("2b41", "Sleep Activity Summary Data"),
    ("2b42", "Physical Activity Monitor Control Point"),
    ("2b43", "Activity Current Session"),
    ("2b44", "Physical Activity Session Descriptor"),
    ("2b45", "Preferred Units"),
    ("2b46", "High Resolution Height"),
    ("2b47", "Middle Name"),
    ("2b48", "Stride Length"),
    ("2b49", "Handedness"),
    ("2b4a", "Device Wearing Position"),
    ("2b4b", "Four Zone Heart Rate Limits"),
    ("2b4c", "High Intensity Exercise Threshold"),
    ("2b4d", "Activity Goal"),
    ("2b4e", "Sedentary Interval Notification"),
    ("2b4f", "Caloric Intake"),
    ("2b50", "TMAP Role"),
    ("2b51", "Audio Input State"),
    ("2b52", "Gain Settings Attribute"),
    ("2b53", "Audio Input Type"),
    ("2b54", "Audio Input Status"),
    ("2b55", "Audio Input Control Point"),
    ("2b56", "Audio Input Description"),
    ("2b57", "Volume State"),
    ("2b58", "Volume Control Point"),
    ("2b59", "Volume Flags"),
    ("2b5a", "Volume Offset State"),
    ("2b5b", "Audio Location"),
    ("2b5c", "Volume Offset Control Point"),
    ("2b5d", "Audio Output Description"),
    ("2b5e", "Set Identity Resolving Key"),
    ("2b5f", "Coordinated Set Size"),
    ("2b60", "Set Member Lock"),
    ("2b61", "Set Member Rank"),
    ("2b62", "Encrypted Data Key Material"),
    ("2b63", "Apparent Energy 32"),
    ("2b64", "Apparent Power"),
    ("2b65", "Live Health Observations"),
    ("2b66", "CO₂ Concentration"),
    ("2b67", "Cosine of the Angle"),
    ("2b68", "Device Time Feature"),
    ("2b69", "Device Time Parameters"),
    ("2b6a", "Device Time"),
    ("2b6b", "Device Time Control Point"),
    ("2b6c", "Time Change Log Data"),
    ("2b6d", "Media Player Name"),
    ("2b6e", "Media Player Icon Object ID"),
    ("2b6f", "Media Player Icon URL"),
    ("2b70", "Track Changed"),
    ("2b71", "Track Title"),
    ("2b72", "Track Duration"),
    ("2b73", "Track Position"),
    ("2b74", "Playback Speed"),
    ("2b75", "Seeking Speed"),
    ("2b76", "Current Track Segments Object ID"),
    ("2b77", "Current Track Object ID"),
    ("2b78", "Next Track Object ID"),
    ("2b79", "Parent Group Object ID"),
    ("2b7a", "Current Group Object ID"),
    ("2b7b", "Playing Order"),
    ("2b7c", "Playing Orders Supported"),
    ("2b7d", "Media State"),
    ("2b7e", "Media Control Point"),
    ("2b7f", "Media Control Point Opcodes Supported"),
    ("2b80", "Search Results Object ID"),
    ("2b81", "Search Control Point"),
    ("2b82", "Energy 32"),
    ("2b83", "Media Player Icon Object Type"),
    ("2b84", "Track Segments Object Type"),
    ("2b85", "Track Object Type"),
    ("2b86", "Group Object Type"),
    ("2b87", "Constant Tone Extension Enable"),
    ("2b88", "Advertising Constant Tone Extension Minimum Length"),
    ("2b89", "Advertising Constant Tone Extension Minimum Transmit Count"),
    ("2b8a", "Advertising Constant Tone Extension Transmit Duration"),
    ("2b8b", "Advertising Constant Tone Extension Interval"),
    ("2b8c", "Advertising Constant Tone Extension PHY"),
    ("2b8d", "Bearer Provider Name"),
    ("2b8e", "Bearer UCI"),
    ("2b8f", "Bearer Technology"),
    ("2b90", "Bearer URI Schemes Supported List"),
    ("2b91", "Bearer Signal Strength"),
    ("2b92", "Bearer Signal Strength Reporting Interval"),
    ("2b93", "Bearer List Current Calls"),
    ("2b94", "Content Control ID"),
    ("2b95", "Status Flags"),
    ("2b96", "Incoming Call Target Bearer URI"),
    ("2b97", "Call State"),
    ("2b98", "Call Control Point"),
    ("2b99", "Call Control Point Optional Opcodes"),
    ("2b9a", "Termination Reason"),
    ("2b9b", "Incoming Call"),
    ("2b9c", "Call Friendly Name"),
    ("2b9d", "Mute"),
    ("2b9e", "Sink ASE"),
    ("2b9f", "Source ASE"),
    ("2ba0", "ASE Control Point"),
    ("2ba1", "Broadcast Audio Scan Control Point"),
    ("2ba2", "Broadcast Receive State"),
    ("2ba3", "Sink PAC"),
    ("2ba4", "Sink Audio Locations"),
    ("2ba5", "Source PAC"),
    ("2ba6", "Source Audio Locations"),
    ("2ba7", "Available Audio Contexts"),
    ("2ba8", "Supported Audio Contexts"),
    ("2ba9", "Ammonia Concentration"),
    ("2baa", "Carbon Monoxide Concentration"),
    ("2bab", "Methane Concentration"),
    ("2bac", "Nitrogen Dioxide Concentration"),
    ("2bad", "Non-Methane Volatile Organic Compounds Concentration"),
    ("2bae", "Ozone Concentration"),
    ("2baf", "Particulate Matter - PM1 Concentration"),
    ("2bb0", "Particulate Matter - PM2.5 Concentration"),
    ("2bb1", "Particulate Matter - PM10 Concentration"),
    ("2bb2", "Sulfur Dioxide Concentration"),
    ("2bb3", "Sulfur Hexafluoride Concentration"),
    ("2bb4", "Hearing Aid Features"),
    ("2bb5", "Hearing Aid Preset Control Point"),
    ("2bb6", "Active Preset Index"),
    ("2bb7", "Stored Health Observations"),
    ("2bb8", "Fixed String 64"),
    ("2bb9", "High Temperature"),
    ("2bba", "High Voltage"),
    ("2bbb", "Light Distribution"),
    ("2bbc", "Light Output"),
    ("2bbd", "Light Source Type"),
    ("2bbe", "Noise"),
    ("2bbf", "Relative Runtime In A Correlated Color Temperature Range"),
    ("2bc0", "Time Second 32"),
    ("2bc1", "VOC Concentration"),
    ("2bc2", "Voltage Frequency"),
    ("2bc3", "Battery Critical Status"),
    ("2bc4", "Battery Health Status"),
    ("2bc5", "Battery Health Information"),
    ("2bc6", "Battery Information"),
    ("2bc7", "Battery Level Status"),
    ("2bc8", "Battery Time Status"),
    ("2bc9", "Estimated Service Date"),
    ("2bca", "Battery Energy Status"),
    ("2bcb", "Observation Schedule Changed"),
    ("2bcc", "Current Elapsed Time"),
    ("2bcd", "Health Sensor Features"),
    ("2bce", "GHS Control Point"),
    ("2bcf", "LE GATT Security Levels"),
    ("2bd0", "ESL Address"),
    ("2bd1", "AP Sync Key Material"),
    ("2bd2", "ESL Response Key Material"),
    ("2bd3", "ESL Current Absolute Time"),
    ("2bd4", "ESL Display Information"),
    ("2bd5", "ESL Image Information"),
    ("2bd6", "ESL Sensor Information"),
    ("2bd7", "ESL LED Information"),
    ("2bd8", "ESL Control Point"),
    ("2bd9", "UDI for Medical Devices"),
    ("2bda", "GMAP Role"),
    ("2bdb", "UGG Features"),
    ("2bdc", "UGT Features"),
    ("2bdd", "BGS Features"),
    ("2bde", "BGR Features"),
    ("2bdf", "Cosine of the Angle 16"),
];

pub fn detect_capabilities(services: &[String], tx_power: Option<i8>) -> Vec<String> {
    let mut capabilities = Vec::new();
    let service_map = get_service_map();
    
    for service_uuid in services {
        let uuid_lower = service_uuid.to_lowercase();
        let uuid_short = if uuid_lower.len() >= 8 {
            &uuid_lower[4..8]
        } else {
            &uuid_lower
        };
        
        if let Some(&capability_name) = service_map.get(uuid_short) {
            capabilities.push(capability_name.to_string());
        }
    }
    
    if tx_power.is_some() { 
        capabilities.push("Transmit Power Control".to_string()); 
    }
    
    if !services.is_empty() && !capabilities.iter().any(|c| c.contains("Generic")) {
        capabilities.push("GATT Services".to_string());
    }
    
    capabilities
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_battery_service() {
        let services = vec!["0000180f-0000-1000-8000-00805f9b34fb".to_string()];
        let caps = detect_capabilities(&services, None);
        assert!(caps.contains(&"Battery Service".to_string()));
    }

    #[test]
    fn test_hid_device() {
        let services = vec!["00001812-0000-1000-8000-00805f9b34fb".to_string()];
        let caps = detect_capabilities(&services, None);
        assert!(caps.contains(&"Human Interface Device".to_string()));
    }

    #[test]
    fn test_tx_power() {
        let services = vec![];
        let caps = detect_capabilities(&services, Some(-5));
        assert!(caps.contains(&"Transmit Power Control".to_string()));
    }

    #[test]
    fn test_generic_gatt_fallback() {
        let services = vec!["802a0000-4ef4-4e59-b573-2bed4a4ac159".to_string()];
        let caps = detect_capabilities(&services, None);
        assert!(caps.contains(&"GATT Services".to_string()));
    }
}
